---
title: "BDP2-448 Lovasz"
date: "2019-07-20"
author: Benjamin Chan (chanb@ohsu.edu)
output:
  html_document:
    toc: true
    theme: simplex
---



# Import data


```r
getwd()
```

```
## [1] "C:/Users/Ben/Google Drive/Work/BDP2-448-Lovasz"
```

```r
f <- "data/raw/Becky-Bedding Exposure Study Data for Stats.2.xlsx"
```

Import data file *data/raw/Becky-Bedding Exposure Study Data for Stats.2.xlsx*


```r
df <- f %>% read_excel()
```

```
## readxl works best with a newer version of the tibble package.
## You currently have tibble v1.4.2.
## Falling back to column name repair from tibble <= v1.4.2.
## Message displays once per session.
```

```r
oldnames <- names(df)
newnames <- c("id",
              "sex",
              "time",
              "bedding",
              "order",
              "room",
              "foodIntakeNormalized",
              "orts",
              "foodIntakeRaw",
              "cumulativeFoodIntakeNormalized")
names(df) <- newnames
data.frame(oldnames, newnames) %>% kable()
```



|oldnames                                         |newnames                       |
|:------------------------------------------------|:------------------------------|
|Mouse ID                                         |id                             |
|Sex                                              |sex                            |
|Time (hr)                                        |time                           |
|Bedding                                          |bedding                        |
|Order                                            |order                          |
|Housing Room                                     |room                           |
|Normalized food intake (mg food/g BW)            |foodIntakeNormalized           |
|Orts (g)                                         |orts                           |
|Raw food intake (g)                              |foodIntakeRaw                  |
|Normalized cumulative food intake (mg food/g BW) |cumulativeFoodIntakeNormalized |

Remove outlier


```r
df %>%
  dplyr::select(id, sex, time, bedding, foodIntakeNormalized) %>%
  filter(id == 42 & bedding == "B") %>%
  kable()
```

```
## Warning: package 'bindrcpp' was built under R version 3.5.2
```



| id|sex | time|bedding | foodIntakeNormalized|
|--:|:---|----:|:-------|--------------------:|
| 42|M   |    2|B       |             21.24892|
| 42|M   |    4|B       |            137.03382|
| 42|M   |   12|B       |            -63.03972|
| 42|M   |   24|B       |             23.99276|
| 42|M   |   36|B       |            128.67490|
| 42|M   |   48|B       |             10.18150|

```r
df <-
  df %>%
  filter(!(id == 42 & bedding == "B"))
```

Plot data.


```r
G <-
  df %>%
  ggplot() +
  aes(x = time, y = foodIntakeNormalized, color = bedding) +
  geom_line(aes(group = id), alpha = 1/4) +
  geom_boxplot(aes(group = time)) +
  facet_grid(sex ~ bedding) +
  scale_color_brewer(palette = "Set1") +
  scale_x_continuous("Time\n(hours)", breaks = c(2, 4, 12, 24, 36, 48)) +
  scale_y_continuous("Food intake, normalized\n(mg food/g body weight)") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
ggsave("figures/lineplot.png", dpi = 300)
```

```
## Saving 7 x 7 in image
```

```r
ggsave("figures/lineplot.svg", dpi = 300)
```

```
## Saving 7 x 7 in image
```

```
## Warning: package 'gdtools' was built under R version 3.5.2
```


```r
G
```

![plot of chunk lineplot](figures/lineplot-1.png)


# New analysis

Prior analysis is archived in commit `f3ce92`.

On Thu, May 2, 2019 at 12:44 PM Becky Lovasz <lovasz@ohsu.edu> wrote:

> Hi Ben,
>  
> My project was put on the back burner for a while, and I'm picking it back up
> again. I discussed the results below with my research advisor. Can you please
> compare normalized food intake for Bedding A vs. Bedding B, regardless of
> bedding exposure order, at each time point separately? We'd like to see males
> only, females only, and all mice combined. Thanks for your help!



```r
random <- formula(~ 1 | id)
cs <-
  corSymm(form = random, fixed = FALSE) %>%
  Initialize(data = df)
ctrl <- lmeControl(opt = "optim",
                   maxIter = 500, msMaxIter = 500,
                   tolerance = 1e-6, niterEM = 25, msMaxEval = 200, msTol = 1e-7)
testContrast <- function (nlmeObj, contrast) {
  require(multcomp)
  g <- glht(nlmeObj, linfct = c(contrast)) %>% summary()
  x <- g[["test"]][["coefficients"]]
  dir <- ifelse(x > 0, "higher", "lower")
  s <- g[["test"]][["sigma"]]
  p <- g[["test"]][["pvalues"]][[1]]
  result <- data.frame(contrast = contrast,
                       coefficient = x,
                       sigma = s,
                       pvalue = p,
                       effsize = abs(x),
                       direction = dir,
                       stringsAsFactors = FALSE)
  rownames(result) <- NULL
  result
}
```

## All mice combined

Use `nlme::lme()`.
Specify a general correlation structure with `corSymm()`.
Use this output.


```r
fixed <- formula(foodIntakeNormalized ~
                   bedding +
                   time +
                   bedding * time)
M <-
  df %>%
  mutate(time = factor(time)) %>%
  lme(fixed, data = ., random = random, correlation = cs, control = ctrl)
M %>% 
  tidy() %>%
  filter(effect == "fixed") %>%
  kable(digits = 3)
```



|effect |group |term            | estimate| std.error|  df| statistic| p.value|
|:------|:-----|:---------------|--------:|---------:|---:|---------:|-------:|
|fixed  |fixed |(Intercept)     |   12.009|     1.999| 423|     6.008|   0.000|
|fixed  |fixed |beddingB        |   -0.069|     2.114| 423|    -0.033|   0.974|
|fixed  |fixed |time4           |   -3.229|     1.906| 423|    -1.695|   0.091|
|fixed  |fixed |time12          |   67.429|     3.333| 423|    20.234|   0.000|
|fixed  |fixed |time24          |   11.936|     2.637| 423|     4.526|   0.000|
|fixed  |fixed |time36          |  118.441|     3.172| 423|    37.338|   0.000|
|fixed  |fixed |time48          |    3.342|     2.974| 423|     1.124|   0.262|
|fixed  |fixed |beddingB:time4  |    5.972|     2.674| 423|     2.233|   0.026|
|fixed  |fixed |beddingB:time12 |   -1.335|     3.340| 423|    -0.400|   0.690|
|fixed  |fixed |beddingB:time24 |   -6.099|     2.483| 423|    -2.456|   0.014|
|fixed  |fixed |beddingB:time36 |    1.803|     3.864| 423|     0.467|   0.641|
|fixed  |fixed |beddingB:time48 |    5.783|     4.362| 423|     1.326|   0.186|

```r
testBeddingEffect <- 
  bind_rows(testContrast(M, "beddingB = 0"),
            testContrast(M, "beddingB + beddingB:time4 = 0"),
            testContrast(M, "beddingB + beddingB:time12 = 0"),
            testContrast(M, "beddingB + beddingB:time24 = 0"),
            testContrast(M, "beddingB + beddingB:time36 = 0"),
            testContrast(M, "beddingB + beddingB:time48 = 0"))
testBeddingEffect %>% kable(digits = 3)
```



|contrast                       | coefficient| sigma| pvalue| effsize|direction |
|:------------------------------|-----------:|-----:|------:|-------:|:---------|
|beddingB = 0                   |      -0.069| 2.114|  0.974|   0.069|lower     |
|beddingB + beddingB:time4 = 0  |       5.903| 1.770|  0.001|   5.903|higher    |
|beddingB + beddingB:time12 = 0 |      -1.404| 2.924|  0.631|   1.404|lower     |
|beddingB + beddingB:time24 = 0 |      -6.168| 2.520|  0.014|   6.168|lower     |
|beddingB + beddingB:time36 = 0 |       1.734| 3.475|  0.618|   1.734|higher    |
|beddingB + beddingB:time48 = 0 |       5.714| 3.067|  0.062|   5.714|higher    |

```r
test1 <- testBeddingEffect
```

## By sex

Use `nlme::lme()`.
Specify a general correlation structure with `corSymm()`.
Use this output.


```r
fixed <- formula(foodIntakeNormalized ~
                   bedding +
                   time +
                   sex +
                   bedding * time +
                   bedding * sex +
                   sex * time +
                   bedding * time * sex)
M <-
  df %>%
  mutate(time = factor(time)) %>%
  lme(fixed, data = ., random = random, correlation = cs, control = ctrl)
M %>% 
  tidy() %>%
  filter(effect == "fixed") %>%
  kable(digits = 3)
```



|effect |group |term                 | estimate| std.error|  df| statistic| p.value|
|:------|:-----|:--------------------|--------:|---------:|---:|---------:|-------:|
|fixed  |fixed |(Intercept)          |   14.728|     2.767| 412|     5.322|   0.000|
|fixed  |fixed |beddingB             |   -4.916|     2.778| 412|    -1.770|   0.078|
|fixed  |fixed |time4                |   -4.227|     2.704| 412|    -1.563|   0.119|
|fixed  |fixed |time12               |   70.537|     4.636| 412|    15.215|   0.000|
|fixed  |fixed |time24               |   16.446|     3.627| 412|     4.535|   0.000|
|fixed  |fixed |time36               |  122.335|     4.270| 412|    28.652|   0.000|
|fixed  |fixed |time48               |   -0.057|     3.932| 412|    -0.015|   0.988|
|fixed  |fixed |sexM                 |   -4.611|     3.935|  38|    -1.172|   0.249|
|fixed  |fixed |beddingB:time4       |    9.344|     3.725| 412|     2.509|   0.012|
|fixed  |fixed |beddingB:time12      |    2.898|     4.605| 412|     0.629|   0.530|
|fixed  |fixed |beddingB:time24      |   -7.123|     3.500| 412|    -2.035|   0.043|
|fixed  |fixed |beddingB:time36      |    7.871|     5.446| 412|     1.445|   0.149|
|fixed  |fixed |beddingB:time48      |   19.282|     5.462| 412|     3.530|   0.000|
|fixed  |fixed |beddingB:sexM        |    9.694|     3.967| 412|     2.444|   0.015|
|fixed  |fixed |time4:sexM           |    2.112|     3.826| 412|     0.552|   0.581|
|fixed  |fixed |time12:sexM          |   -7.571|     6.577| 412|    -1.151|   0.250|
|fixed  |fixed |time24:sexM          |  -10.346|     5.139| 412|    -2.013|   0.045|
|fixed  |fixed |time36:sexM          |  -10.412|     6.049| 412|    -1.721|   0.086|
|fixed  |fixed |time48:sexM          |    5.765|     5.563| 412|     1.036|   0.301|
|fixed  |fixed |beddingB:time4:sexM  |   -6.733|     5.304| 412|    -1.269|   0.205|
|fixed  |fixed |beddingB:time12:sexM |   -8.596|     6.568| 412|    -1.309|   0.191|
|fixed  |fixed |beddingB:time24:sexM |    2.122|     5.001| 412|     0.424|   0.672|
|fixed  |fixed |beddingB:time36:sexM |  -12.094|     7.739| 412|    -1.563|   0.119|
|fixed  |fixed |beddingB:time48:sexM |  -26.667|     7.789| 412|    -3.424|   0.001|

```r
testBeddingEffect <- 
  bind_rows(testContrast(M, "beddingB = 0"),
            testContrast(M, "beddingB + beddingB:time4 = 0"),
            testContrast(M, "beddingB + beddingB:time12 = 0"),
            testContrast(M, "beddingB + beddingB:time24 = 0"),
            testContrast(M, "beddingB + beddingB:time36 = 0"),
            testContrast(M, "beddingB + beddingB:time48 = 0"),
            testContrast(M, "beddingB + beddingB:sexM = 0"),
            testContrast(M, "beddingB + beddingB:sexM + beddingB:time4:sexM = 0"),
            testContrast(M, "beddingB + beddingB:sexM + beddingB:time12:sexM = 0"),
            testContrast(M, "beddingB + beddingB:sexM + beddingB:time24:sexM = 0"),
            testContrast(M, "beddingB + beddingB:sexM + beddingB:time36:sexM = 0"),
            testContrast(M, "beddingB + beddingB:sexM + beddingB:time48:sexM = 0"))
testBeddingEffect %>% kable(digits = 3)
```



|contrast                                            | coefficient| sigma| pvalue| effsize|direction |
|:---------------------------------------------------|-----------:|-----:|------:|-------:|:---------|
|beddingB = 0                                        |      -4.916| 2.778|  0.077|   4.916|lower     |
|beddingB + beddingB:time4 = 0                       |       4.429| 2.508|  0.077|   4.429|higher    |
|beddingB + beddingB:time12 = 0                      |      -2.018| 4.148|  0.627|   2.018|lower     |
|beddingB + beddingB:time24 = 0                      |     -12.038| 3.341|  0.000|  12.038|lower     |
|beddingB + beddingB:time36 = 0                      |       2.955| 5.053|  0.559|   2.955|higher    |
|beddingB + beddingB:time48 = 0                      |      14.366| 4.025|  0.000|  14.366|higher    |
|beddingB + beddingB:sexM = 0                        |       4.778| 2.832|  0.092|   4.778|higher    |
|beddingB + beddingB:sexM + beddingB:time4:sexM = 0  |      -1.955| 4.514|  0.665|   1.955|lower     |
|beddingB + beddingB:sexM + beddingB:time12:sexM = 0 |      -3.818| 6.247|  0.541|   3.818|lower     |
|beddingB + beddingB:sexM + beddingB:time24:sexM = 0 |       6.900| 4.885|  0.158|   6.900|higher    |
|beddingB + beddingB:sexM + beddingB:time36:sexM = 0 |      -7.316| 7.466|  0.327|   7.316|lower     |
|beddingB + beddingB:sexM + beddingB:time48:sexM = 0 |     -21.889| 6.821|  0.001|  21.889|lower     |

```r
test2 <- testBeddingEffect
```


# Interpretation

Using a model that does not distinguish male and female mice, there is a
slight difference in food intake by bedding type at 24 and 48 hours.
At 24 hours, food intake is
6.17 mg/g
lower
with bedding type B compared to A
(p-value: 0.014).
At 48 hours, food intake is
5.71 mg/g
higher
with bedding type B compared to A
(p-value: 0.062).

Among female mice, there is a difference in food intake by bedding type at 24
and 48 hours.
At 24 hours, food intake is
12 mg/g
lower
with bedding type B compared to A
(p-value: 0.00031).
At 48 hours, food intake is
14.4 mg/g
higher
with bedding type B compared to A
(p-value: 0.00036).

Among male mice, there is a difference in food intake by bedding type at 2 and 48 hours.
At 2 hours, food intake is
4.78 mg/g
higher
with bedding type B compared to A
(p-value: 0.092).
At 48 hours, food intake is
21.9 mg/g
lower
with bedding type B compared to A
(p-value: 0.0013).


# R session information

For debugging purposes.


```
## [1] "Run time: 2019-07-20 11:56:04"
```

```
## R version 3.5.1 (2018-07-02)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17134)
## 
## Matrix products: default
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] gdtools_0.1.7     bindrcpp_0.2.2    multcomp_1.4-8   
##  [4] TH.data_1.0-9     MASS_7.3-50       survival_2.43-3  
##  [7] mvtnorm_1.0-8     broom.mixed_0.2.3 nlme_3.1-137     
## [10] lme4_1.1-19       Matrix_1.2-14     svglite_1.2.1    
## [13] broom_0.5.1       readxl_1.2.0      forcats_0.3.0    
## [16] stringr_1.3.1     dplyr_0.7.8       purrr_0.2.5      
## [19] readr_1.3.1       tidyr_0.8.2       tibble_1.4.2     
## [22] ggplot2_3.1.0     tidyverse_1.2.1   magrittr_1.5     
## [25] checkpoint_0.4.5  rmarkdown_1.11    knitr_1.21       
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.19       lubridate_1.7.4    lattice_0.20-35   
##  [4] zoo_1.8-4          assertthat_0.2.0   digest_0.6.18     
##  [7] R6_2.3.0           cellranger_1.1.0   plyr_1.8.4        
## [10] backports_1.1.3    evaluate_0.12      coda_0.19-2       
## [13] highr_0.7          httr_1.4.0         pillar_1.3.1      
## [16] rlang_0.3.0.1      lazyeval_0.2.1     rstudioapi_0.8    
## [19] minqa_1.2.4        nloptr_1.2.1       labeling_0.3      
## [22] splines_3.5.1      TMB_1.7.15         munsell_0.5.0     
## [25] compiler_3.5.1     modelr_0.1.2       xfun_0.4          
## [28] pkgconfig_2.0.2    htmltools_0.3.6    tidyselect_0.2.5  
## [31] glmmTMB_0.2.2.0    codetools_0.2-15   crayon_1.3.4      
## [34] withr_2.1.2        grid_3.5.1         jsonlite_1.6      
## [37] gtable_0.2.0       scales_1.0.0       cli_1.0.1         
## [40] stringi_1.2.4      reshape2_1.4.3     xml2_1.2.0        
## [43] generics_0.0.2     sandwich_2.5-0     RColorBrewer_1.1-2
## [46] tools_3.5.1        glue_1.3.0         hms_0.4.2         
## [49] colorspace_1.3-2   rvest_0.3.2        bindr_0.1.1       
## [52] haven_2.0.0
```
