library("knitr")
library("rmarkdown")
opts_chunk$set(fig.path = "figures/")
knit("scripts/BDP2-448.Rmd", output = "docs/BDP2-448.md")
pandoc("docs/BDP2-448.md", format = "docx")
# system("pandoc --template=GitHub.html5 --self-contained docs/BDP2-448.md -o docs/BDP2-448.html")
system("pandoc --self-contained docs/BDP2-448.md -o docs/BDP2-448.html")
