---
title: "BDP2-448 Lovasz"
date: "2019-02-13"
author: Benjamin Chan (chanb@ohsu.edu)
output:
  html_document:
    toc: true
    theme: simplex
---



# Import data


```r
getwd()
```

```
## [1] "C:/Users/Ben/Google Drive/Work/BDP2-448-Lovasz/scripts"
```

```r
f <- "../data/raw/Becky-Bedding Exposure Study Data for Stats.2.xlsx"
```

Import data file *../data/raw/Becky-Bedding Exposure Study Data for Stats.2.xlsx*


```r
df <- f %>% read_excel()
```

```
## readxl works best with a newer version of the tibble package.
## You currently have tibble v1.4.2.
## Falling back to column name repair from tibble <= v1.4.2.
## Message displays once per session.
```

```r
oldnames <- names(df)
newnames <- c("id",
              "sex",
              "time",
              "bedding",
              "order",
              "room",
              "foodIntakeNormalized",
              "orts",
              "foodIntakeRaw",
              "cumulativeFoodIntakeNormalized")
names(df) <- newnames
data.frame(oldnames, newnames) %>% kable()
```



|oldnames                                         |newnames                       |
|:------------------------------------------------|:------------------------------|
|Mouse ID                                         |id                             |
|Sex                                              |sex                            |
|Time (hr)                                        |time                           |
|Bedding                                          |bedding                        |
|Order                                            |order                          |
|Housing Room                                     |room                           |
|Normalized food intake (mg food/g BW)            |foodIntakeNormalized           |
|Orts (g)                                         |orts                           |
|Raw food intake (g)                              |foodIntakeRaw                  |
|Normalized cumulative food intake (mg food/g BW) |cumulativeFoodIntakeNormalized |

Plot data.


```r
G <-
  df %>%
  ggplot() +
  aes(x = time, y = foodIntakeNormalized, group = id, color = bedding) +
  geom_line(alpha = 1/4) +
  facet_wrap(~ bedding) +
  scale_color_brewer(palette = "Set1") +
  scale_x_continuous("Time\n(hours)", breaks = c(2, 4, 12, 24, 36, 48)) +
  scale_y_continuous("Food intake, normalized\n(mg food/g body weight)") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank())
ggsave("../figures/lineplot.png", width = 7, height = 4, dpi = 300)
ggsave("../figures/lineplot.svg", width = 7, height = 4, dpi = 300)
```

```
## Warning: package 'gdtools' was built under R version 3.5.2
```


```r
G
```

![plot of chunk lineplot](figures/lineplot-1.png)


# Setup data


```r
t <- 36
```

Reshape data to mouse-level analytic data set.
Data point at t = 36 is used to evaluate difference between A and B bedding types.

Outcome variable is `diff`,
which is the difference between normalized food intake at t = 36 under A-B bedding types.

* Positive values indicate the mouse ate more at t = 36 with bedding type A
* Negative values indicate the mouse ate more at t = 36 with bedding type B


```r
dfA <-
  df %>%
  filter(time == t) %>%
  filter(bedding == "A") %>%
  select(id, foodIntakeNormalized) %>%
  rename(A = foodIntakeNormalized)
```

```
## Warning: package 'bindrcpp' was built under R version 3.5.2
```

```r
dfB <-
  df %>%
  filter(time == t) %>%
  filter(bedding == "B") %>%
  select(id, foodIntakeNormalized) %>%
  rename(B = foodIntakeNormalized)
dfDiff <-
  merge(dfA, dfB, by = "id") %>%
  mutate(diff = A - B)
covariates <-
  df %>%
  filter(order == 1) %>%
  select(id, sex, order, bedding, room) %>%
  unique() %>%
  mutate(isBeddingAFirst = order == 1 & bedding == "A")
dfDiff <-
  merge(dfDiff, covariates, by = "id") %>%
  select(-c(order, bedding))
```

Exploratory comparisons.


```r
dfDiff %>%
  group_by(sex) %>%
  summarize(n = n(), mean = mean(diff), sd = sd(diff)) %>%
  kable(digits = 1)
```



|sex |  n| mean|   sd|
|:---|--:|----:|----:|
|F   | 20| -9.0| 41.3|
|M   | 20|  2.3| 28.8|

```r
dfDiff %>%
  group_by(room) %>%
  summarize(n = n(), mean = mean(diff), sd = sd(diff)) %>%
  kable(digits = 1)
```



|room  |  n| mean|   sd|
|:-----|--:|----:|----:|
|0543  | 15|  2.0| 29.0|
|0545C | 25| -6.6| 39.3|

```r
dfDiff %>%
  group_by(isBeddingAFirst) %>%
  summarize(n = n(), mean = mean(diff), sd = sd(diff)) %>%
  kable(digits = 1)
```



|isBeddingAFirst |  n|  mean|   sd|
|:---------------|--:|-----:|----:|
|FALSE           | 20| -27.9| 31.4|
|TRUE            | 20|  21.2| 18.7|


# Model A-B difference at t = 36


```r
M <- lm(diff ~ 1, data = dfDiff) 
M %>% tidy() %>% kable(digits = 3)
```



|term        | estimate| std.error| statistic| p.value|
|:-----------|--------:|---------:|---------:|-------:|
|(Intercept) |   -3.376|     5.635|    -0.599|   0.553|

There appears to be **no** significant difference in the amount of food intake at t = 36.
Normalized food intake is higher with bedding type B by
3.38 mg/g
(p-value = 0.55).


```r
lm(diff ~ sex, data = dfDiff) %>% tidy() %>% kable(digits = 3)
```



|term        | estimate| std.error| statistic| p.value|
|:-----------|--------:|---------:|---------:|-------:|
|(Intercept) |   -9.044|     7.967|    -1.135|   0.263|
|sexM        |   11.336|    11.267|     1.006|   0.321|

```r
lm(diff ~ room, data = dfDiff) %>% tidy() %>% kable(digits = 3)
```



|term        | estimate| std.error| statistic| p.value|
|:-----------|--------:|---------:|---------:|-------:|
|(Intercept) |    1.960|     9.257|     0.212|   0.833|
|room0545C   |   -8.537|    11.709|    -0.729|   0.470|

The difference is still not significant after adjusting for sex or room.


```r
M <- lm(diff ~ isBeddingAFirst, data = dfDiff)
M %>% tidy() %>% kable(digits = 3)
```



|term                | estimate| std.error| statistic| p.value|
|:-------------------|--------:|---------:|---------:|-------:|
|(Intercept)         |  -27.929|     5.783|    -4.830|       0|
|isBeddingAFirstTRUE |   49.106|     8.178|     6.005|       0|



However, the difference appears to depend on which bedding type the mouse experiences first.
Mice that experience bedding type A first have higher food intakes at t = 36 with bedding type A:
21.2 mg/g
(p-value = 0.00076)
Mice that experience bedding type B first have higher food intakes at t = 36 with bedding type B:
27.9 mg/g
(p-value = 2.3e-05)

This suggests that a crossover design might not be the most optimal study design for this research question.

An alternative analysis is to assume a model that ignores the cross-sectional study design.
Instead, the model includes `order` as a fixed effect and an interaction between `bedding` and `order`.
The model also includes a random intercept effect for mouse.


# Model normalized food intake at t = 36

This model is a longitudinal model where each mouse contributes 2 data points,
one for each bedding type (A, B).
The model includes an `order` effect and an interaction between `bedding` and `order`.


```r
dfRanEff <-
  df %>%
  filter(time == t) %>%
  select(id, foodIntakeNormalized, order, bedding, sex, room) %>%
  mutate(order = factor(order))
dfRanEff %>%
  group_by(order, bedding) %>%
  summarize(n = n(), mean = mean(foodIntakeNormalized), sd = sd(foodIntakeNormalized)) %>%
  kable(digits = 1)
```



|order |bedding |  n|  mean|   sd|
|:-----|:-------|--:|-----:|----:|
|1     |A       | 20| 143.9| 18.3|
|1     |B       | 20| 143.2| 23.6|
|2     |A       | 20| 115.3| 21.8|
|2     |B       | 20| 122.7| 18.8|

A t = 36, normalized food intake for the mice under bedding type A is almost identical to the mice under bedding type B at the start of the experiment (`order` = 1).
After crossover (`order` = 2) there is a slightly lower normalized food intake among the mice under bedding type A compared to bedding type B.


```r
dfRanEff <-
  dfRanEff %>%
  mutate(orderRev = factor(order, levels = c(2, 1)))
M <-
  lmer(foodIntakeNormalized ~ bedding + orderRev + bedding * orderRev + (1 | id), 
       data = dfRanEff)
M %>% 
  tidy(conf.int = TRUE, effects = "fixed") %>% 
  mutate(pvalue = pt(statistic, df = 1, lower.tail = FALSE)) %>% 
  kable(digits = 3)
```



|effect |term               | estimate| std.error| statistic| conf.low| conf.high| pvalue|
|:------|:------------------|--------:|---------:|---------:|--------:|---------:|------:|
|fixed  |(Intercept)        |  115.292|     4.638|    24.857|  106.201|   124.383|  0.013|
|fixed  |beddingB           |    7.411|     6.559|     1.130|   -5.445|    20.268|  0.231|
|fixed  |orderRev1          |   28.588|     6.559|     4.358|   15.732|    41.445|  0.072|
|fixed  |beddingB:orderRev1 |   -8.071|    10.258|    -0.787|  -28.176|    12.035|  0.712|



After crossover, mice under bedding type B had higher normalized food intake compared to bedding type A:
7.41 mg/g
(p-value = 0.23)



Before crossover, there was virtually no difference between normalized food intake by bedding type:
-0.659 mg/g
(p-value = 0.53)


# R session information

For debugging purposes.


```
## [1] "Run time: 2019-02-13 22:34:46"
```

```
## R version 3.5.1 (2018-07-02)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17134)
## 
## Matrix products: default
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] bindrcpp_0.2.2    gdtools_0.1.7     broom.mixed_0.2.3
##  [4] lme4_1.1-19       Matrix_1.2-14     svglite_1.2.1    
##  [7] broom_0.5.1       readxl_1.2.0      forcats_0.3.0    
## [10] stringr_1.3.1     dplyr_0.7.8       purrr_0.2.5      
## [13] readr_1.3.1       tidyr_0.8.2       tibble_1.4.2     
## [16] ggplot2_3.1.0     tidyverse_1.2.1   magrittr_1.5     
## [19] checkpoint_0.4.5  rmarkdown_1.11    knitr_1.21       
## 
## loaded via a namespace (and not attached):
##  [1] TMB_1.7.15         tidyselect_0.2.5   xfun_0.4          
##  [4] reshape2_1.4.3     glmmTMB_0.2.2.0    splines_3.5.1     
##  [7] haven_2.0.0        lattice_0.20-35    colorspace_1.3-2  
## [10] generics_0.0.2     htmltools_0.3.6    rlang_0.3.0.1     
## [13] nloptr_1.2.1       pillar_1.3.1       glue_1.3.0        
## [16] withr_2.1.2        RColorBrewer_1.1-2 modelr_0.1.2      
## [19] bindr_0.1.1        plyr_1.8.4         munsell_0.5.0     
## [22] gtable_0.2.0       cellranger_1.1.0   rvest_0.3.2       
## [25] coda_0.19-2        evaluate_0.12      labeling_0.3      
## [28] highr_0.7          Rcpp_0.12.19       scales_1.0.0      
## [31] backports_1.1.3    jsonlite_1.6       hms_0.4.2         
## [34] digest_0.6.18      stringi_1.2.4      grid_3.5.1        
## [37] cli_1.0.1          tools_3.5.1        lazyeval_0.2.1    
## [40] crayon_1.3.4       pkgconfig_2.0.2    MASS_7.3-50       
## [43] xml2_1.2.0         lubridate_1.7.4    minqa_1.2.4       
## [46] assertthat_0.2.0   httr_1.4.0         rstudioapi_0.8    
## [49] R6_2.3.0           nlme_3.1-137       compiler_3.5.1
```
